[package]
name = "wy_common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# itertools = "0.10.2"
wy_failure = { path = "../failure" }
serde = { version = "1", features = ["derive"] }